
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  target 'FateChangerAppIOS' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod "youtube-ios-player-helper", "~> 0.1.4"
  end
  target 'FateChangerAppIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FateChangerAppIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

